[workspace]
authors = ["jdspell <jdspell@iu.edu>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "life"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
modular = ">=25.5.0.dev2025062815,<26"
python = ">=3.11,<3.13"
pygame = ">=2.6.1,<3"
